disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Abegail"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "abegail-logo.png"
author = { name = "Abegail Santos", image = "abby_bnw.jpg" }
secondaryLogo = "abegail-logo.png"
