[[main]]
none = "none"

[[main]]
name = "Blog"
pageRef = "Blog"
identifier = "GP2TGLzeBf"
weight = 9999

[[main]]
pre = "github"
url = "https://www.github.com/asnts18"
identifier = "8sWVk1j9Ze"
weight = 9999

[[main]]
pre = "linkedin"
url = "https://www.linkedin.com/in/abegailsantos"
identifier = "9htBEqJSrS"
weight = 9999

[[footer]]
none = "none"
